//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoLocate
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoute
    {
        public UserRoute()
        {
            this.UserRouteCoords = new HashSet<UserRouteCoord>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<UserRouteCoord> UserRouteCoords { get; set; }
    }
}
