//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoLocate
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCoord
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Accuracy { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<double> Heading { get; set; }
        public Nullable<double> Speed { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
